Better err msg when @ann is on wrong type of node
k14s/ytt pull request #518
Opened 2021-10-22 00:08 UTC by vmunishwar

#325

2021-10-23 20:35 UTC, cppforlife commented on pkg/workspace/doc_extractor.go
> +					return fmt.Errorf(errMsg, annName, node.UserFriendlyName(), node.GetPosition().GetFile(), node.GetPosition().LineNum(), annName)
take a look at https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/yttlibrary/overlay/op.go#L86 for how we typically stringify positions.

2021-10-25 22:16 UTC, vmunishwar commented on pkg/workspace/doc_extractor.go
> +					return fmt.Errorf(errMsg, annName, node.UserFriendlyName(), node.GetPosition().GetFile(), node.GetPosition().LineNum(), annName)
Thank you. Found a method AsCompactString to use. I have updated the code.

2021-10-26 15:58 UTC, pivotaljohn requested changes
Just a few renames and this will be good to go!

2021-10-26 15:58 UTC, pivotaljohn commented on pkg/cmd/template/cmd_data_values_test.go
> +
```suggestion
	expectedErrorMessage := "Found @data/values on map item (data.yml:4); only documents (---) can be annotated with @data/values"

```

Let's make node types lowercase as they are ordinary (not proper) nouns.

2021-10-26 15:58 UTC, pivotaljohn commented on pkg/yamlmeta/ast.go
> +	UserFriendlyName() string
```suggestion
	DisplayName() string
```

Played with this together: is `DisplayName` a better name for this method?

2021-10-26 18:30 UTC, vmunishwar commented on pkg/cmd/template/cmd_data_values_test.go
> +
Thank you. I have made the changes.

2021-10-26 18:31 UTC, vmunishwar commented on pkg/yamlmeta/ast.go
> +	UserFriendlyName() string
Done. Thank you.

2021-10-26 23:05 UTC, pivotaljohn approved these changes
Congratulations on your first merged contribution to `ytt`, @vmunishwar!

This looks great. Every internal detail we can convert into something more intuitive (like referring to a thing as a "map item" rather than a "yamlmeta.MapItem") makes `ytt` _that_ much friendlier and easier to use. 👍🏻

2021-10-26 23:06 UTC, merged