Change org and repository name in 0.44.x line
k14s/ytt pull request #800
Opened 2023-01-26 18:41 UTC by vmunishwar

Signed-off-by: kumari tanushree <ktanushree@vmware.com>

2023-01-26 21:32 UTC, joaopapereira requested changes
I left some comments but apart from that it looks good

2023-01-26 21:32 UTC, joaopapereira commented on .goreleaser.yml
> +      - -X github.com/carvel-dev/ytt/pkg/version.Version={{ .Version }}
This should not be changed until we change the module name

2023-01-26 21:32 UTC, joaopapereira commented on README.md
> +* Backlog: [See what we're up to]([https://app.zenhub.com/workspaces/carvel-backlog-6013063a24147d0011410709/board?repos=173207060). (Note: we use ZenHub which requires GitHub authorization](https://
```suggestion
* Backlog: [See what we're up to]([https://app.zenhub.com/workspaces/carvel-backlog-6013063a24147d0011410709/board?repos=173207060). (Note: we use ZenHub which requires GitHub authorization](https://github.com/orgs/carvel-dev/projects/1/views/1?filterQuery=repo%3A%22carvel-dev%2Fytt%22)).
```

2023-01-26 21:32 UTC, joaopapereira commented on docs/dev.md
> +  1. Start the server: `godoc -http=:6060` and visit [`http://localhost:6060/pkg/github.com/carvel-dev/ytt/`](http://localhost:6060/pkg/github.com/carvel-dev/ytt/).
This should not be changed until we change the module name

2023-01-26 21:32 UTC, joaopapereira commented on docs/dev.md
> +The go module was renamed from `github.com/k14s` to `github.com/carvel-dev/ytt` in February 2022. Carvel started out as a suite named "k14s" short for Kubernetes Tools.
This should not be changed until we change the module name

2023-01-26 21:32 UTC, joaopapereira commented on hack/build-binaries.sh
> +LDFLAGS="-X github.com/carvel-dev/ytt/pkg/version.Version=$VERSION"
This should not be changed until we change the module name

2023-01-27 01:09 UTC, jtigger approved these changes
Thanks for pruning this back to just what's needed to get our CI working again.

👍

2023-01-27 01:11 UTC, merged