Export named validations to openApi properties
k14s/ytt pull request #899
Opened 2024-03-25 22:01 UTC by peschmae

Fixes #897

2024-03-26 06:24 UTC, prembhaskal commented
will try to review this week.

2024-03-26 07:05 UTC, peschmae commented
Just saw the linting errors, and will look into them.

Should I squash my commits and force push, or is it fine to have mutliple commits, and the will be squashed when merged?

2024-04-02 04:52 UTC, prembhaskal commented
you can have multiple commits and then squash them before merging.

2024-04-08 14:06 UTC, peschmae commented
Any change to get a review on this?
Compared to #901 this is a smaller change and would allow to integrate the conversion from openapi to json schema, in a separate tool if the other PR wouldn't be merged.

2024-04-08 20:08 UTC, joaopapereira requested changes
Added some nitpick changes more stylistic than anything.
Generally, the PR looks good.

2024-04-08 20:08 UTC, joaopapereira commented on pkg/validations/validate.go
> +
nit:
```suggestion
```

2024-04-08 20:08 UTC, joaopapereira commented on pkg/validations/validate.go
> +
nit:
```suggestion
```

2024-04-08 20:08 UTC, joaopapereira commented on pkg/validations/validate.go
> +
nit:
```suggestion
```

2024-04-08 20:08 UTC, joaopapereira commented on pkg/validations/validate.go
> +
nit: 
```suggestion
```

2024-04-08 21:07 UTC, peschmae commented
Ammended whitespace cleanup into latest commit, and force pushed

2024-04-09 10:27 UTC, sethiyash approved these changes
LGTM!

2024-04-10 14:16 UTC, cppforlife approved these changes

2024-04-10 15:17 UTC, joaopapereira approved these changes
LGTM

2024-04-10 15:17 UTC, merged